### ISSUE TITLE
Path Finder: Support non-trivial paths patterns.

### ISSUE THREAD

**Issue by dantleech** [phpactor/phpactor#1076]
The test-path scheme for the language-server-phpactor-extensions is incompatible with the path finder.

e,g,
```
src/ModuleName/Blah/Foo.php`
tests/Module/Unit/Blah/FooTest.php`
```

would only be possible by supporting multiple segments:

```
src/<module>/<subpath>.php
tests/<module>/Unit/<subpath>.php
```

which isn't possible currently as we only allow `<kernel>`

**Comment by elythyr** [comment]
It would be an interesting feature.
For the mentioned case I would have seen `tests/Unit/Module` instead, seems to make more sens to group tests by type, often they are not even in `tests` but `specs` or `features`, etc.

The difficulty with the example `src/<module>/<subpath>.php` is to determine which part should be greedy
Meaning we would need an alternate syntax to recognize the depth of each segment, in glob it's simple `src/*/**/*.php`.
Maybe something like `src/<module:*>/<subpath>.php` and defaulting the segments to `**/*` to preserve BC ?

We could then have things like `packages/<package:**>/src/<subpath>.php` which in a monolith like the one I work with which does not have any rule about what subpath could be would be really convinient.

But I'm wondering when do we have a need for this ?
I guess for navigation ?
Then I would argue that the responsibility is to the client and not the server.
We have great tools like projectionist, which can easily be combined with UltiSnips to create skeletons, fzf to find related files, etc.
Also, the configuration depend so much on the project since there is no real standard about how to organize the filesystem that it does not seem realistic to ever reach a point where it will be working without heavy configuration from the user.

**Comment by dantleech** [comment]
This is already solved actually:  https://github.com/phpactor/path-finder you can use arbitrary tokens.

**Comment by dantleech** [comment]
Needs better documentation though
