### ISSUE TITLE
Diagnostics: `iterable` wrongly identified as "non-existing class"

### ISSUE THREAD

**Issue by dantleech** [phpactor/phpactor#1101]
![image](https://user-images.githubusercontent.com/530801/93206897-0c105f80-f752-11ea-9359-34263b759296.png)

It is present in the phpstorm stubs, so should be identified here.

**Comment by elythyr** [comment]
I think that's the reason we got the error, the stub consider it (or the use we made of the stubs) as a class.
I remember that at some point phpactor would add some `use iterable;` when implementing contracts and stuff like that, but I can't reproduce so that must have been fixed since.

**Comment by dantleech** [comment]
Phpactor [generates](https://github.com/phpactor/language-server-phpactor-extensions/blob/master/lib/LanguageServerCodeTransform/CodeAction/ImportNameProvider.php#L103) this error. The reason is because it's searching for the name using the index, but the stubs are not indexed.

**Comment by elythyr** [comment]
What about excluding this case like it's done here: https://github.com/phpactor/code-transform/blob/41071cee6da50937e68e8a6391d03719e2e649c7/lib/Adapter/WorseReflection/Helper/WorseUnresolvableClassNameFinder.php#L83
Something like:
```php
if ('iterable' === (string) $name) {
    return $unresolvedNames
}
```
Since `iterable` is a reserved keyword I think it's OK to handle it this way.

If it's OK for you I will do the PR, it's a really quick fix and adding a test is just as simple.

**Comment by dantleech** [comment]
`iterable` is part of the Jetbrains PHPStorm stubs. The problem is that these are not currently indexed and the diagnostics use the indexer exclusively (it would be too slow otherwise).

So the solution is to ensure that the stubs are indexed.

Apparently the option to configure this has been implemented [here](https://github.com/phpactor/indexer-extension/blob/master/lib/Extension/IndexerExtension.php#L96).

So it might be as simple as including the Phpactor `vendor/jetbrains/phpstorm-stubs` directory [here](https://github.com/phpactor/phpactor/blob/4159ba543a79bd0bc3322707f4f97a3e60e7e85d/lib/Phpactor.php#L249)

**Comment by elythyr** [comment]
Does it make sense to put the stubs in the index though ?
Would it not make more sense to query the index, as it is done currently, and if not found in the index then check the stub ?
Or aggregate the result of the index with the content of the stubs in some way.

No matter all that, I try your idea and it didn't worked.
I defined the parameter with `%applicaiton_root%/vendor/jetbrains/phpstorm-strubs` and rebuild my index.
I still got the error, then I tried to take a quick look at how the parameter was used and it seems like it will only be used to define glob patterns that must be match in order for a file to be returned by the `FilesystemFileListProvider`.
But the `Filesystem` created for the index, take a `SimpleFileListeProvider` which only provide the files from the project root.

So I'm not sure if I didn't understood how it works or if the `PARAM_STUB_PATHS` is not used properly...

**Comment by elythyr** [comment]
There is some progress :D
![image](https://user-images.githubusercontent.com/11501572/97805370-fbf70580-1c55-11eb-975b-79e397f04945.png)

**Comment by dantleech** [comment]
"Object" is a special type, probably enough to update WR to include iterable as a reserved name too.

**Comment by elythyr** [comment]
`object` is not considered a `QualifiedName` by the parser if I understood correctly what was going on.
But I don't see what you mean by updating WR, for me this is what is happening (ignoring functions and constant cases):
1. We use Toleran Parser (TP) to retrieve all nodes of type `QualifiedName`
2. We resolve the name with TP
3. If the resolved name is `static`, `self` or `parent` we consider it OK
4. If the name was unresolved by TP it's resolved as being in the current namespace
5. We check that the resolved name is found with the `Reflector` (`StubSourceLocator`, `IndexerClassSourceLocator`, etc.)

So the only time WR is involved is at stage `5.` which is already too late because TP would have resolved the name to `Current\Namespace\iterable` at stage `1.`

Therfore what needs to be fixed is the name resolution, we could use the `TolerantQualifiedNameResolver` and update it to resolve `iterable` to `iterable` or even `\iterable`.
That would fix the issue and I think it our best option since it means that we would have a "correct" name resolution anywhere for `iterable`.

But I still don't get why TR consider a pseudo-type as a qualified name ><

**Comment by dantleech** [comment]
Probably worth submitting a PR to TolerantParser, in the meantime one way forward might be to add a test on WR and fix it there.

**Comment by elythyr** [comment]
I started to work on the TolerantParser, the changes are quite easy, but the implications of returning a token instead of a node might slow things down.
There already was an issue about that, since 2017...

**Comment by elythyr** [comment]
> in the meantime one way forward might be to add a test on WR and fix it there.

How do you see that exactly ?
You want to ignore the namespace if it ends by `iterable` in the `StubSourceLocator` so that it would recognize it ?
This would be valid right now but in PHP 8 we will be able to use reserved keyword in the namespaces so it won't work.

I will prepare a PR with a fix in the `TolerantQualifiedNameResolver` because it makes more sens to me and that would allow me to not have those errors locally.
I will update the PR once I understand how you want to f

**Comment by dantleech** [comment]
Just had a closer look, maybe simply adding it here with `self`, `parent` etc. ?

https://github.com/phpactor/code-transform/blob/5a3df8a9c9d9bffe0478a37891b534027c2982dc/lib/Adapter/WorseReflection/Helper/WorseUnresolvableClassNameFinder.php#L83-L85

**Comment by elythyr** [comment]
In the PR I did that but in the `TolerantQualifiedNameResolver`, this way we will benefit from it in multiple places.

**Comment by dantleech** [comment]
ok, makes sense I think :+1:
