### ISSUE TITLE
Index files outside project directory

### ISSUE THREAD

**Issue by norival** [phpactor/phpactor#1113]
Hi!

I was wondering if it is possible to index files outside project directory in order to have completion and code navigation. I'm working on projects that depend on other php files that are in a different location (these projects are not using composer).

Everyone here is using phpstorm and it is possible to add these files as 'External librairies' to have autocompletion of classes and methods and code navigation.

Thanks! :)

**Comment by elythyr** [comment]
Hi,

It's currently not possible.
I guess we could add this feature, like we did in order to index the stubs, but I'm not sure it's a good idea right now.
The issue is that I'm almost certain we still have features that do not rely on the index.

So if we add this possibility we will have inconsistent behavior because the features relying on the index will be aware of the external code while other features won't.

@dantleech You have a better vision of project as a all, do you think it would behave properly ?
Maybe we can add the feature but specify that it is only supported when used as a LSP server ?
Even though some RPC features start using the indexer so we will still have the same issue.

I realize that the [indexer configuration](https://phpactor.readthedocs.io/en/develop/reference/indexer.html#configuration) as not been updated, only the [configuration reference](https://phpactor.readthedocs.io/en/develop/reference/configuration.html#indexer-stub-paths)
Also, it's not possible to override or change the value of `indexer.stub_paths` because of:
https://github.com/phpactor/phpactor/blob/6ee1603677757a1a9d42dfbd9f924347d6196a3e/lib/Phpactor.php#L79
I guess that if we don't want it to be configurable by the user we should not expose it in the configuration, since it's made as a list I think you intended it to be configurable.

So to resume:
* Is it possible to add external sources to the indexer without having a strange behavior ?
* If so, maybe we should rename the `stub_paths` to something like `external_sources`
* Should the user be able to add its own stub paths ? (to fix the current behavior)

**Comment by dantleech** [comment]
Yes, adding it to stub paths would accomplish what is required I think. Maybe it should be renamed, and maybe the phpstorn stubs can be added programatically rather than via config

**Comment by norival** [comment]
Hi! Thank you for your answers and all the details :) It would be great to have this feature. Is there any way I can help?

**Comment by dantleech** [comment]
For now you could try setting:

```
{
    "indexer.stub_paths": [
        "/absolute/path/to/phpactor/vendor/jetbrains/phpstorm-stubs",
        "/path/to/your/external/files"
    ]
}
```

**Comment by elythyr** [comment]
We need to fix the initialization of the config first, if I understand how the config loader works, we first load the config from the config files, then we override the stubs then we load the extension configs.

**Comment by norival** [comment]
> For now you could try setting:
> 
> ```
> {
>     "indexer.stub_paths": [
>         "/absolute/path/to/phpactor/vendor/jetbrains/phpstorm-stubs",
>         "/path/to/your/external/files"
>     ]
> }
> ```

It does not change

**Comment by dantleech** [comment]
You'll need to do a --reset, e.g. `:CocCommand phpactor.reindex` or `$ phpactor index:build --reset`

**Comment by norival** [comment]
Ok, I tried to reset the index, but it is still the same. I tried to query with `phpactor index:query` and it does not find the references either.

**Comment by dantleech** [comment]
are you on `develop`, in `master` `stub_paths` does not work. Try `phpactor index:search` (`index:query` requires FQNs - it not very well named)

**Comment by norival** [comment]
Ah, I was on `master`, sorry. I switched to `develop` but it is still not working. It does not find the references in vim, nor with `phpactor index:search`. The `index:build --reset` command says there are 306 files in the index whereas there are around 5000 php files in the external libraries.

**Comment by dantleech** [comment]
if you run `index:build --reset --verbose` you should at least see the `phpstorm-stub` files being indexed, the path may need to be absolute, what does ` phpactor config:dump  --config-only | jq '.["indexer.stub_paths"]'` say?

**Comment by norival** [comment]
Yes, the `phpstorm-stub` files are shown with the `--verbose` option. Here is the output of `phpactor config:dump --config-only | jq '.["indexer.stub_paths"]'`:

```
[                                                                   
  "/home/xlaviron/.local/share/nvim/plugged/phpactor/vendor/jetbrains/phpstorm-stubs"
] 
```
I tried changing the value in the config file, and the output is always the same.

**Comment by dantleech** [comment]
ah ok, then I misunderstood how it currently works:

https://github.com/phpactor/phpactor/blob/6ee1603677757a1a9d42dfbd9f924347d6196a3e/lib/Phpactor.php#L79-L81

we could append the stubs here if the key exists rather than overwriting -- that might be an intermediate solution.

**Comment by norival** [comment]
Ok! I tried setting the paths directly here :

https://github.com/phpactor/phpactor/blob/6ee1603677757a1a9d42dfbd9f924347d6196a3e/lib/Phpactor.php#L79-L81

and the files are indexed! Completion and go to definition work fine :) I had to increase php's memory limit though.
