### ISSUE TITLE
Indexing crashes the language-server with status 255.

### ISSUE THREAD

**Issue by pablobc-mx** [phpactor/phpactor#1114]
I'm trying to use the language server with a laravel project using Emacs with [eglot](https://github.com/joaotavora/eglot). Even though Emacs has [phpactor.el](https://github.com/emacs-php/phpactor.el) it doesn't work like I want to, and I want to use the language server for a more consistent experience.
The problem is, when eglot starts the server it exits abruptly after idexing ~28% of the project (2000 files).
```
[eglot] Connected! Server `EGLOT (proyecto/php-mode)' now managing `php-mode' buffers in project `proyecto'.
[eglot] Server reports (type=3): Indexing "6974" PHP files
[eglot] Server reports (type=3): Indexed 500/6974 (7.17%)
[eglot] Server reports (type=3): Indexed 1000/6974 (14.34%)
[eglot] Server reports (type=3): Indexed 1500/6974 (21.51%)
[eglot] Server reports (type=3): Indexed 2000/6974 (28.68%)
[jsonrpc] Server exited with status 255
```
I tried running it with the tcp server and got `[jsonrpc] Server exited with status 256` instead. It doesn't say much as to the cause of the problem.
```
[INFO][347124.966710] OUT: {
    "method": "window\/showMessage",
    "params": {
        "type": 3,
        "message": "Indexed 1500\/6974 (21.51%)"
    },
    "jsonrpc": "2.0"
}
[INFO][347131.277387] OUT: {
    "method": "window\/showMessage",
    "params": {
        "type": 3,
        "message": "Indexed 2000\/6974 (28.68%)"
    },
    "jsonrpc": "2.0"
}
```
And here's the output of phpactor status.
```
[pablo@pablo-pc proyecto]$ phpactor status
Version: 2403e25 (5 days ago) fix-phpactor-Status-use-the-configured-paths-1112
Filesystems: git, simple, composer
Working directory: /home/pablo/Prog/php/proyecto

Config files (missing is not bad):

  ✘ /home/pablo/.config/phpactor/phpactor.json
  ✘ /home/pablo/.config/phpactor/phpactor.yml
  ✘ /home/pablo/Prog/php/proyecto/.phpactor.json
  ✘ /home/pablo/Prog/php/proyecto/.phpactor.yml

Diagnostics:

  ✔ Composer detected - Phpactor could work faster without an index
  ✔ Git detected - enables faster refactorings in your repository scope!
  ✔ XDebug is disabled. XDebug has a negative effect on performance.
```
When I run it in a small project it indexes around ~400 files with no problem.

**Comment by artelkr** [comment]
[mentioned](https://github.com/phpactor/phpactor/issues/1092#issuecomment-710052424) this earlier
btw, in lumen projects indexing goes well (but vim connection to lsp fails); does not work on laravel projects (fail after indexing symphony iconv polyfill)

**Comment by dantleech** [comment]
As mentioned in the post mentioned above, the best way to debug is to run the LS as a TCP server with `-v`. You should then see a stack trace.

I'll try testing with a Laravel project also.

**Comment by elythyr** [comment]
I tried with the following project: https://github.com/framgia/laravel-test-examples
The indexer does not start when I open the project...
When I try to index manually with `phpactor index:build --reset` I have an error:

![image](https://user-images.githubusercontent.com/11501572/97103901-d6935600-16af-11eb-9088-fa288cff9463.png)

We might want to exclude unreadable files ?

**Comment by dantleech** [comment]
Could probably ignore hidden (`.`) files too.

**Comment by elythyr** [comment]
Addin the flag `RecursiveIteratorIterator::CATCH_GET_CHILD` to the `RecursiveIteratorIterator` does the trick.
But I wonder if we should not try to catch it ourself in the iterator so that we can log it ?

At the top of my head I don't at any reason not to exclude doted directories indeed.
If we go this way we might also consider ignoring directories not related to a project and created by the frameworks ?
At least for the most used one, like `var/` from Symfony, `node_modules` from Node, etc ?

**Comment by dantleech** [comment]
We already have config to ignore patterns: https://github.com/phpactor/indexer-extension/blob/master/lib/Extension/IndexerExtension.php#L81

I guess it would make sense to ignore common folder names from the project directory.

**Comment by elythyr** [comment]
Yes, I was thinking about that config exactly ;)
So I guess we should try to make a list and decide what we will exclude from it:
- `/var/**/*` exlude everything from the `var` directory at the root of the project only
- `/**/node_modules/**/*` exclude everything from any `node_modules` directory
- `/**/DoctrineMigrations/**/*` exclude everything from any `DoctrineMigrations` directory

**Comment by dantleech** [comment]
- `app/cache`

I would keep DoctrineMigrations and any other folder which may contain non-obfuscated PHP code (you can inject the container into a migration ... )

Worth checking how the globbing works, as not sure ignoring `node_modules` would provide any significant benefit performance wise.

**Comment by elythyr** [comment]
Updated list:
- `/var/**/*` exlude everything from the `var` directory at the root of the project only
- `/**/node_modules/**/*` exclude everything from any `node_modules` directory
- `/app/cache/**/*` exclude everything in the the app/cahce` directory at the root of the project

OK for the migrations, I removed it from the list.
For the `node_modules` it's mainly because there can be a BUNCH of files in there, no need to waist even a few seconds on them.
But also because of https://github.com/phpactor/phpactor/issues/1063#issuecomment-709312012: my index got quit big because of the `var/log` directory not being ignored, but there is no PHP files in their and some how the index was huge because my log directory was huge (I never cleaned my bedroom...)

What is the `app/cache` for ?
I would like to be able to add the reason for each case when doing the PR so that we won't forgot why we did it :)

**Comment by dantleech** [comment]
`app/cache` is Symfony 2 (and possibly 3)

**Comment by elythyr** [comment]
Not Symfony 3, we are still with 3.4 at work :'( 
So I can confirm that ;)
Not sure we should care about Symfony 2 bt default, the user can configure it's own exclusions if needed.
We should focus on sensible defaults for the most used frameworks and see later if there is other needs.

**Comment by dantleech** [comment]
:+1:

**Comment by pablobc-mx** [comment]
So I finally figured out what caused the crash after manually indexing the project. The language server ran out of memory while indexing my project. Allocating more memory fixed the issue, either with `php -d memory_limit=XXXM /path/to/phpactor language-server` or editing your `php.ini`. I'll close the issue.

**Comment by dantleech** [comment]
Well, we could probably mitigate this issue by keeping track of the used memory

**Comment by dantleech** [comment]
It will now show the memory usage and the memory limit as it is indexing `[coc.nvim] Indexed 500/6744 (7.41%) 141/500 mb` for example. Should be in `develop` soon,
