### ISSUE TITLE
Language server import class

### ISSUE THREAD

**Issue by indeedhat** [phpactor/phpactor#1116]
Hi im probably missing something here but how do i import a class when using the language server?

In the docs on the develop branch it states that the import class code action is available (https://phpactor.readthedocs.io/en/develop/lsp/support.html) but i cant for the life of me work out what i need to do to run it.

my assumption would be something along the lines of `nmap <Leader>u <Plug>(coc-import-class)`

Thanks.

**Comment by dantleech** [comment]
code actions, for example

```
nmap <Leader>ca <Plug>(coc-codeaction)
xmap <Leader>ca  v<Plug>(coc-codeaction-selected)
nmap <Leader>ca  v<Plug>(coc-codeaction-selected)
```
I use `<Leader>ca` to calculate the code actions for the entire document. It will offer to "fix" various things, if there are missing classes it will offer to import them.

In addition, classes should be imported automatically when you select them from the auto-complete.

**Comment by indeedhat** [comment]
Thanks, the code action works perfectly.

I did notice that there was a PR that mentioned it auto importing but that didnt work for me.
After some further investigation it seems to be due to me having remapped the keys for the pop up menu.

**Comment by dantleech** [comment]
Then I guess this ticket should be re-purposed to updating the support document to link to the relevant sections of the doc (if they exist)

**Comment by indeedhat** [comment]
i tried greping the project and i don't think that they do

**Comment by elythyr** [comment]
For CoC:
* https://github.com/neoclide/coc.nvim#example-vim-configuration
* https://github.com/neoclide/coc.nvim/wiki/Completion-with-sources#limitation-of-cocnvims-completion
* https://github.com/neoclide/coc.nvim/wiki/F.A.Q#function-parameterauto-import-not-work-on-complete-done

I don't think we should gave too much information about how to configure a client, otherwise the burden of maintaining this information will be on us.
Maybe we can instead add links to relevant parts in the clients documentation, even then if the links are dead we will have to maintain them.

@dantleech up to you, if you want I will do a PR to add the above links, otherwise I think we can close the issue.

**Comment by dantleech** [comment]
But it's not clear that you need code-actions in order to import classes, etc.

- `code-action` short cuts should be added to the [example CoC configuration](https://phpactor.readthedocs.io/en/develop/lsp/vim.html) (or we can remove it in favor of a link to CoC, but the Phpactor example is a lot less daunting.
- There should be documentation on the currently available code-actions (import class, implement contracts etc) and diagnostics - and we should hyperlink to these from the `lsp-support` page.

**Comment by elythyr** [comment]
I agree a list of available code actions would be nice.
I will try to do it and add it in the LSP support page.

For the doc I will update the CoC configuration we have to add links.

**Comment by dantleech** [comment]
Probably better as a separate page - `lsp/code-actions.rst` or similar, with links as necessary from the support page.

**Comment by elythyr** [comment]
@dantleech I think we can close it.

**Comment by dantleech** [comment]
Thanks, I updated to link to the new page from the lsp-support page.
