### ISSUE TITLE
Signature helper shows wrong signature sometimes

### ISSUE THREAD

**Issue by dantleech** [phpactor/phpactor#1168]
![image](https://user-images.githubusercontent.com/530801/103484772-3f522980-4de9-11eb-9bc7-1ba430c426db.png)

**Comment by BladeMF** [comment]
The test case is this:
```php
<?php function hello() {}; function hi() {}; hello(hi(<>
```
and also
```php
<?php function hello() {}; function hi() {}; hello(hi(<>)
```
In that case, because the argument list is null (empty), it shows the signature of `hi`. If an argument is created for `hi(`, then it shows the right signature. If `hi` has no arguments there is no way to see its signature from that position.

**Comment by dantleech** [comment]
Another example (not fixed by the above PR)

![image](https://user-images.githubusercontent.com/530801/103818597-bfce8f80-5060-11eb-8182-d99c01a7d7da.png)

**Comment by BladeMF** [comment]
Oh! Interesting! I know, because it is a constructor! I think I've checked for a function only. Will add a test case.

**Comment by BladeMF** [comment]
Found a bug :-( This doesn't work :-( My check was dumb.
```php
f1(
    f2(
        <>
    )
);
```

**Comment by camilledejoye** [comment]
I never had the time to look into it but I think that when you start typing the second argument of the inner function call then the signature shown is the correct one (to validate).
If that's the case it might be because the parser is not able to recognize the inner function call as such ?

**Comment by BladeMF** [comment]
> I never had the time to look into it but I think that when you start typing the second argument of the inner function call then the signature shown is the correct one (to validate).

Correct. The problem is only when there are no arguments.

> If that's the case it might be because the parser is not able to recognize the inner function call as such ?

That case up there fails because my fix was checking if the position of the cursor was next to the brace, but I didn't account for any whitespaces that might be there. I haven't had the time to fix it. 

Here is another example:

![image](https://user-images.githubusercontent.com/12109622/104726535-7525d500-573c-11eb-8163-e5956d7c8492.png)
![image](https://user-images.githubusercontent.com/12109622/104726545-79ea8900-573c-11eb-930a-226d0701ae60.png)
