### ISSUE TITLE
Tab on completion disregards existing braces

### ISSUE THREAD

**Issue by BladeMF** [phpactor/phpactor#1172]
In this case:
```php
$this->assertInstan<>($textEdit);
```
if I hit `tab` on the completion list, I get this result:
```php
$this->assertInstanceOf($expected, $actual)($textEdit);
```
The fact that the next character after the selection was an open brace should've been honored and only the method name should be inserted.

**Comment by camilledejoye** [comment]
You should be able to "solve" the issue by not validating the completion.
Select the correct choice so that the text in inserted in your buffer but do not validate (in your case with `Tab`).

A proper fix will require a bit of rework, currently the parameters are added as a snippet but when generating the snippet we only have access to the `Suggestion` (if I'm not mistaken).
A solution might be to use the Tolerant parser to check if the completed node already has parameters but currently we generate the snippet in the completion handler and not when the `Suggestion` is generated (which is where we have access to the parser).
We could rework this part to gave the responsibility of this generation to the completors but it feels like breaking SRP.
Or we could introduce a new set of services only responsible for "refining" the suggestions ?

**Comment by BladeMF** [comment]
I agree that the `SnippetFormatter` is a bit short of information, but when you think about it in this case we want only the name, so we don't really need a formatter.
