### ISSUE TITLE
Suggestions list loses first result when paginated

### ISSUE THREAD

**Issue by dshoreman** [phpactor/phpactor#1218]
If you call `phpactor#UseAdd()` on a symbol with enough results to push it over many pages, the `-- More --` prompt pushes the first result off the screen.

You can still enter `1` as an option, you just won't know what "1" relates to:

![image](https://user-images.githubusercontent.com/1521802/109952203-786a2580-7cd6-11eb-8b00-873cc18b811f.png)

Easier to reproduce *without* the patch for #1216 since you can create a bunch of dummy `Foo.php` copies like `Foo.php.kitten`, and it should detect them.

**Comment by dantleech** [comment]
Not sure what the solution for this would be as we use the built-in `inputlist` function: https://github.com/phpactor/phpactor/blob/add34185f2b66c4dc4cc02ffa4a46e28f43f6da0/autoload/phpactor/input/list.vim#L1-L3

**Comment by camilledejoye** [comment]
@dshoreman I think you're able to scroll this list. Not sure how because I never use it but it might be worth checking the manual.

We really need to take care of those lists issues, I still haven't found a solution for the fzf issue with multiple lists and I don't think we will ever found one...
Maybe we could take a look at https://github.com/liuchengxu/vim-clap instead.
Since it runs directly in vim I hope we won't have the same issues, it forces us to add an extra dependency though but it should be acceptable as an optional feature.

**Comment by dantleech** [comment]
As an aside - I see us moving to the language server in the long term - which will eventually make the VIM plugin redundant - we don't need to worry about the client at all. Not opposed to improving the native VIM plugin in the meantime (maybe it stays forever anyway)

**Comment by dshoreman** [comment]
> @dshoreman I think you're able to scroll this list. Not sure how because I never use it but it might be worth checking the manual.
> 
You're right - up arrow works! Not sure why I didn't think to try that...

I'll close this here. The chances of it happening are slim once source-code-filesystem is updated. If it does, pressing up is perfectly acceptable :)

---

@camilledejoye While looking up "those list issues" I found #845, so I'll reply to the rest there to avoid it getting lost
