### ISSUE TITLE
LSP Renaming: Renaming from the index is unreliable 

### ISSUE THREAD

**Issue by dantleech** [phpactor/phpactor#1297]
The indexed based renaming depends on the index (obviously): the indexer can bail out for many reasons and cannot be relied upon currently - even if it were reliable, with a large scale renaming, it would still take some seconds to re-index everything - and if you changed your mind during that time and renamed the renamed symbol it wouldn't work and it would levae your system in an inconsistent state.

The legacy logic is reliable because it checks the existing state of the GIT files _on disk_:

- It is always accurate because it picks up the references whether they are indexed or not. It's _consistent_.
- It only renames files in GIT (depending on configuration).
- It's _mostly_ fast (it filters out source files containing the rename text before parsing them)*

 It has the following limitations:

- It does not take into account open files
- It writes changes directly to disk - if you want to revert it's another rename or a `git --reset`
- *it can be slow if the symbol name is common (it will parse all those files). The indexed renamer suffers slightly less as it has less false positives (it still needs to statically analyse the source code)

For me, both of these are actually advantages (do you really want to see 100 files have been open and modified each time you rename somethig? do you want to save 100 files + those 5 which you don't want to save??? do you want to UNDO 100 files?). IDE should reload the files for you anyway.

However, it would be possible to use the "brute" force approach while taking into account open files, and to have an option to not write the changes to disk in realtime.

**Comment by BladeMF** [comment]
My thoughts on this:
* You can't rely on `git --reset` because you may have had other changes in those files. I can't imagine having to check in everything before renaming.
* VS Code actually requires a single `Ctrl+Z` to undo everything.
* What you are describing is the common problem of all cache - keeping it up to date. The only problem I've noticed  for 7 months with the index is with file renaming - it keeps both entries. While the index **can** become inconsistent, you can always _make_ it consistent by reindexing.

Can you describe the problem/use case that drove you to this solution? That will help me see your point.

Possibly unrelated - the current class mover (the CLI command) is **extremely** slow (it takes minutes) - I am guessing it is not using the index?
