### ISSUE TITLE
laravel go to defination faild

### ISSUE THREAD

**Issue by lhyaax** [phpactor/phpactor#132]
Hey, guy!
I use laravel  framework,
The default demo  

/tests/ExampleTest

`<?php

use Illuminate\Foundation\Testing\WithoutMiddleware;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Illuminate\Foundation\Testing\DatabaseTransactions;

class ExampleTest extends TestCase
{
    /**
     * A basic functional test example.
     *
     * @return void
     */
    public function testBasicExample()
    {
        $this->visit('/')
             ->see('Laravel');
    }
}`
I try to go to defination,
cursor "TestCase"  is work
cursor "visit" or "see"  didn't work

what's wrong?

**Comment by dantleech** [comment]
It's actually goto TYPE. So if the visit method has a return type, then it should go to that. Otherwise it will goto the type of the variable, or the class you use it on. Bit weird I know, but better than nothing. 

Goto definition is planned for the future: https://github.com/phpactor/phpactor/issues/110

**Comment by dantleech** [comment]
Goto definition is now implemented: https://github.com/phpactor/phpactor/blob/master/plugin/README.md#goto-definition
