### ISSUE TITLE
Complete keywords

### ISSUE THREAD

**Issue by przepompownia** [phpactor/phpactor#1554]
![image](https://user-images.githubusercontent.com/11404453/167257621-6f8dea6f-5fb1-4b6d-a2f4-245b90a825a9.png)
Shown on `return` but other completion results as `public`, `abstract`, `interface`, `continue` etc. could be also present where it makes sense.

**Comment by dantleech** [comment]
there is the KeywordCompletor but I disabled it by default because it was completing in unappropriate places. you can turn it on again: https://phpactor.readthedocs.io/en/master/reference/configuration.html#completion-worse-completor-keyword-enabled

but in general the next steps would be improving the context sensitivity of the completors which would include this probably.

**Comment by przepompownia** [comment]
Thanks, I'll enable it and see if appearing results in unappropriate places is better than nothing for me.

**Comment by dantleech** [comment]
note that i've refactored the "keyword" completor to be more context sensitive, and it's missing many keywords currently (and determining the context is a hard problem it seems):

https://github.com/phpactor/phpactor/blob/1c81ce10f78ede5dd52cfa29bf6861410f09ab28/lib/Completion/Bridge/TolerantParser/WorseReflection/KeywordCompletor.php#L15

**Comment by przepompownia** [comment]
Yes, I noticed the mentioned commit days ago and forgot to comment here in the shadow of attention on other issues. 

Currently It works much better than before it, especially function names are not present in return type context.
