### ISSUE TITLE
Cannot infer `foreach` item type from docblock 

### ISSUE THREAD

**Issue by przepompownia** [phpactor/phpactor#1708]
@dantleech thanks for hint from #1687 - more trivial example can be used here.

Given https://github.com/phpactor/phpactor/blob/master/lib/WorseReflection/Tests/Inference/foreach/assigns_type_to_item.test remove the only real assignment:
```php
<?php

/** @var int[] $items */

foreach ($items as $item) {
    wrAssertType("int", $item);
}
```
and run `./vendor/bin/phpunit  lib/WorseReflection/Tests/Inference/SelfTest.php`. https://github.com/phpactor/phpactor/compare/master...przepompownia:infer-foreach-item-from-ddocblock?expand=1

![image](https://user-images.githubusercontent.com/11404453/172360449-8d2f6a59-2928-47fb-90af-fcba327dad33.png)
![image](https://user-images.githubusercontent.com/11404453/172360554-1cb19956-2838-4a75-a5b0-43c71abdb8a4.png)
The variable defined in docblock is recognized independently of real assignment:
![image](https://user-images.githubusercontent.com/11404453/172361238-815af9ad-20e3-49a2-93c7-bca093e4456e.png)

**Comment by dantleech** [comment]
it's because the `VariableWalker` is responsible for parsing the docblock comments and assigning them to subsequent variables, but the `ForEach` node is processed first which uses the `VariableResolver` - to resolve the collection name. The VariableWalker does not process the docblock.

ideally we would remove the historical/evolved distinction between "walkers" and "resolvers" so there would only be Resolvers and this problem would go away.

for the meantime we could:

- make the VariableResolver parse any docblock that "precedes" it - problem is the docblock does not always precede the variable, and could actually be attached to any node (e.g. above it's attached to the `ForEach` statement)

if we do that then we may well VariableWalker and rely solely on the VaraibleResolver moving a bit closer to the goal of removing hte variable walkers completely (the problem is that resolvers cannot create new frames, which walkers can....)

**Comment by przepompownia** [comment]
Works for me :tada: It's useful especially for PHP views.
