### ISSUE TITLE
Handler cancellation

### ISSUE THREAD

**Issue by BladeMF** [phpactor/phpactor#1769]
All handlers should support cancellation. Currently adding a `CancellationToken $cancel` argument to the `HoverHandler` produces an "unresolvable argument" error which I can't understand as `CodeActionHandler`'s same argument works.

**Comment by BladeMF** [comment]
VSCode cancels hovers. I am guessing these are really quick since you may pass over multiple variables. In my prototype I put `delay` and `cancel` check first thing in `call(...)` just to catch quick hovers. In that sense in `AggregateCodeActionProvider` you should check before the provider, rather than after - requests often get delayed by other requests and the code inside `call` is executed considerable time after the actual call to the handler.

**Comment by dantleech** [comment]
feel free to open a PR on language-server

**Comment by BladeMF** [comment]
I think that is in the main repo. I need help with why is `HandlerRunner` throwing the error though. Why is `AggregateCodeActionProvider` being sent that parameter, but not `HoverHandler`?

**Comment by dantleech** [comment]
> canellation tokens not being passed

because: https://github.com/phpactor/language-server/blob/159cb20030695b05271843d27f76d4659ca43a1a/lib/Core/Handler/HandlerMethodRunner.php#L83-L85

we add the cancellation token after resolving the input params to either individual params or a *Params DTO from the LSP specification.

> cancelling at the start of hover

would it also work to cancel for all requests here:

https://github.com/phpactor/language-server/blob/159cb20030695b05271843d27f76d4659ca43a1a/lib/Core/Handler/HandlerMethodRunner.php#L72-L74

**Comment by dantleech** [comment]
closing, if adding cancellation to the main handler method runner would solve this let's try it. feel free to carry on the discussion here.
