### ISSUE TITLE
Code action menu

### ISSUE THREAD

**Issue by JoyceBabu** [phpactor/phpactor#1799]
Currently the vim plugin context menu is appearing as a comma separated list of actions at the bottom of the vim editor.

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/502942/179422983-0766bbd2-3e6e-4db3-bbb8-7f16fe25f361.png">

Is it possible to display these code actions in the COC autocomplete menu? I know about the coc-phpactor plugin, but I would like to use standard VIM plugin since that is recommended.

**Comment by dantleech** [comment]
The LSP server (which serves CoC) and the "legacy" VIM integration are two separate things. Most of the actions above are already integrated via. LSP (the eception being "inflect").

If you use CoC it's very much recommended to use the `coc-phpactor` plugin, we just recommend the native VIM pluign because it currently has some extra functionality, but ultimately it should all be in LSP in the future.
