### ISSUE TITLE
Unknown variable diagnostic and suggested fix

### ISSUE THREAD

**Issue by mamazu** [phpactor/phpactor#2077]
I am a very bad typist and I frequently mess up variable names and then php tells me that my variable is null (in production like environments) because I have a typo.

Is there a reason why phpactor has missing property diagnostics and missing method diagnostics but not missing variable diagnostics?

**Comment by dantleech** [comment]
The reason is that it has "refactorings" to fix these, and in general Phpactor is not intended to replace tools like PHPStan or Psalm, but yes, I think a missing variable diagnostic and a fix for it based on [Levenshtein](https://www.php.net/manual/en/function.levenshtein.php) distance to an existing variable could be useful?

**Comment by mamazu** [comment]
That sounds like a great idea.

**Comment by dantleech** [comment]
Fixed in #2209
