### ISSUE TITLE
Trailing comma in function argument definition is not reported when it is an error in PHP 7.4

### ISSUE THREAD

**Issue by cafce25** [phpactor/phpactor#2460]
```php
<?php
function foo($bar,) {}
```
Is not valid in PHP 7.4:
```none
PHP Parse error:  syntax error, unexpected ')', expecting variable (T_VARIABLE) in Standard input code on line 2
```
however `phpactor` with configuration set to `php.version = '7.4'` doesn't report any error.

```sh
% phpactor config:dump | grep php.version
    "php.version": 7.4,
```

Might be an artifact of running `phpactor` with the system PHP 8.1.25 instead of the configured project php version.

**Comment by dantleech** [comment]
yes, the linter will use the current version of PHP

https://github.com/phpactor/phpactor/blob/1dcb8b2c589912ca8712a75c0a214d365de331fc/lib/Extension/LanguageServerDiagnostics/LanguageServerDiagnosticsExtension.php#L21

otherwise I won't be adding 7.4 features so closing, altough would expect a PR to allow the PHP_BIN to be configured above so you could use a 7.4 php binary for the linter...
