### ISSUE TITLE
Package as a PHAR

### ISSUE THREAD

**Issue by umpirsky** [phpactor/phpactor#26]
Would be cool to provide phar.

**Comment by dantleech** [comment]
Eventually there will be a self-updating PHAR, but it's early days yet.

**Comment by dantleech** [comment]
Also the forthcoming VIM plugin will self-install the application (if that's useful).

**Comment by umpirsky** [comment]
I'm interested into standalone CLI command. I guess other editors will benefit from standalone phar.

**Comment by dantleech** [comment]
Can use https://github.com/humbug/phar-updater

**Comment by umpirsky** [comment]
I used box, but if https://github.com/humbug/phar-updater can provide self-update, that's neat!

**Comment by dantleech** [comment]
Was going to use box (and take same approach as with [phpbench](https://github.com/phpbench/phpbench) which uses the `phar-updater`

**Comment by umpirsky** [comment]
How to install it? It's not on packagist? :)

**Comment by umpirsky** [comment]
@dantleech Thanks, I did do that, just tough packagist availability would attract more users. Thanks for the tool, `class:move` is extremely useful when refactoring!

**Comment by drupol** [comment]
Hey,

I would like to provide this tool in the Nix distribution (Nix and NixOS).
Is this feature still planned?
It would actually be extremely easy for us if the PHAR could be available.

Thanks!

**Comment by dantleech** [comment]
yes I think a PHAR would be a good idea, especially now that Phpactor is a monolithic project with no extensiblity.

**Comment by drupol** [comment]
Cool, let me know here or on Mastodon when it's ready and I'll package it in Nix !

**Comment by dantleech** [comment]
Well, I may not actively work on it. How would it be different from just git clone etc?

**Comment by drupol** [comment]
That's the whole thing actually.

In Nix, when building a package, no network access is allowed to make sure everything is reproducable at 100% (or trying to) and reduce entropy.
Therefore, since it requires dependencies via Composer, this is not going to work as of today.

Having the PHAR would definitely solve this.

**Comment by dantleech** [comment]
hm you still need to download the PHAR? is there a difference between that and `git clone && composer install` in anycase agree it's better a a PHAR.

**Comment by drupol** [comment]
Nix has a special function to download things from the internet (_fetchurl_, _fetchFromGitHub_, ...) and in order to work, a hash needs to be provided, it's mandatory (See an example on how we do with [Composer](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/php-packages/composer/default.nix#L10)).

Having a PHAR is a good idea in this case because this is a self contained program that doesn't need to download anything to work.

**Comment by dantleech** [comment]
the next Phpactor release will come with a PHAR #2281

**Comment by drupol** [comment]
Excellent!

If this PR https://github.com/NixOS/nixpkgs/pull/225401 is not merged in the meantime, I'll provide the derivation.

Basically, this PR will provide a builder for any composer based application, see what it's going to be with PHPActor in here: https://github.com/NixOS/nixpkgs/blob/bedfb144215a15895eaf25833b489d6565da7a0a/pkgs/development/tools/phpactor/default.nix
