### ISSUE TITLE
Method undefined which was implemented in a chain of hierarchy

### ISSUE THREAD

**Issue by qbnil** [phpactor/phpactor#2661]
![изображение](https://github.com/phpactor/phpactor/assets/130576530/f9faaaf7-1476-4d29-84a2-722ef8f1b06b)
The method is showed as undefined, even tho the object - new MailMesage() with $mail variable referencing it.
This is the MailMessage class which extends another class: 
![изображение](https://github.com/phpactor/phpactor/assets/130576530/be0b5b78-74f9-4320-9c77-2eb9c5b7d6c8)
This class on the other hand extends another class:
![изображение](https://github.com/phpactor/phpactor/assets/130576530/88bfb26f-3682-4dab-848d-62d5530d4db9)
And finally the last class implements our needed interface:
![изображение](https://github.com/phpactor/phpactor/assets/130576530/d1af96ff-5523-4dee-98d1-bdaf04d18678)
I guess this should be fixed, thx

**Comment by dantleech** [comment]
what's the return type of `setIdsInData`?

**Comment by dantleech** [comment]
i mean, you call `setIdsInData` which presumably returns a `MessageInterface` (?) it doesn't have to return the _same_ object that is passed in, in which case Phpactor is correct and I suspect PHPStan would complain about the same.

in this case do you need to reassign the `$message` as I imagine it is being modified by reference anyway? otherwise you could use generics in `ObjectService` to make phpactor/phpstan/psalm understand that the type returned is the same as the type that is passed in.
