### ISSUE TITLE
Generate getters / setters through transformation

### ISSUE THREAD

**Issue by Taluu** [phpactor/phpactor#293]
Hello,

Would be quite nice to be able to generate getters (and / or setters) for a classes' attributes. :}

**Comment by dantleech** [comment]
You can already add getters. Just use the context menu on a class property.

By default it will not prefix `get`, but you can configure it as follows:

```
code_transform.refactor.generate_accessor.prefix: get
```

As for setters -- not at the moment.

**Comment by Taluu** [comment]
Oh nice for the getters / accessors. And setters are not really necessary imo.

**Comment by Taluu** [comment]
Hum, just tried and while it's nice to generate said accessor for a property, would also be nice to generate accessors for all properties in one fell swoop (entities...). :}

**Comment by dantleech** [comment]
Meh, maybe a transform for that yeah.

**Comment by elythyr** [comment]
Hi,

I'm working on it currently but I was wondering how to make it accessible.
I already updated the `GenerateAccessorHandler`, the offset is optional now.
If no offset is provided then the user is ask to choose a property in a list (like for the `OverrideMethodHandler`).
Then the offset is retrieved from the property name with `WorseReflection`.

My problem is that I wanted to add a new transformer to handle this scenario.
But the `transform()` method of the `Transformer` must return a `SourceCode` object.

I don't think it's a good idea to provide a way of implementing all geters.
It will add complexity because we will need to first check which property already has an accessor.
Plus it's not a good practice, imo, to create an accessor for every property.

So I really want to let the user choose which property/properties to generate an accessor for.
And I don't want to add a new function just for this use case, as the transform menu seem the right place to put it.

What would you propose ?
I'm not well aware of how phpactor works and the only thing I can think of right know is to change the signature of the `transform()' method to allow either to return a `Handler` object or an `InputCallbackResponse` object.

Another idea might be to generate a dynamic menu.
Like the transform or context menu, but it will provide all possible actions.
It will allow the user to discover easily the functionalities of phpactor as well as providing an easy way to access any of those functionalities in a standard way.
Maybe with a new interface that only ensure a `Response` or something like that ?

**Comment by zordsdavini** [comment]
@elythyr have you succeeded or you abandoned your try?

**Comment by dantleech** [comment]
This is supported as a class refactoring (context menu on the class). When using the [experimental](https://phpactor.github.io/phpactor/vim-plugin/experimental.html) FZF integration you can add all accessors at the same time.

**Comment by zordsdavini** [comment]
Yes, that I found, you already wrote in https://github.com/phpactor/phpactor/issues/293#issuecomment-351970530
Already tried.
I need both setters and getters thou :(
Just wrote small "workaround" plugin for now https://github.com/zordsdavini/vim-symfony-helper

**Comment by dantleech** [comment]
Closing now as this is available as a class refactoring and setters would be a new issue.

**Comment by Einenlum** [comment]
@dantleech Seems the `code_transform.refactor.generate_accessor.prefix: get` config does not upper case the first letter of the property.

`private $quoteId;`

```
    public function getquoteId()
    {
        return $this->quoteId;
    }
```

Is it wanted?

**Comment by Einenlum** [comment]
Oh, found: `code_transform.refactor.generate_accessor.upper_case_first: true`
I guess it could be interesting to set it to true by default, if there is a prefix? Don't know.
I don't think I ever saw a prefix without uppercase after.

**Comment by dantleech** [comment]
yes, i'm not sure why :thinking: happy to accept a PR to default it `true`

**Comment by Einenlum** [comment]
@dantleech Done! :) https://github.com/phpactor/code-transform/pull/33
