### ISSUE TITLE
[VIM] Context menu Input as text instead of modal

### ISSUE THREAD

**Issue by lukepass** [phpactor/phpactor#330]
Hello, when calling the context menu in Vim I get a "popup" modal where I must click buttons:

![image](https://user-images.githubusercontent.com/6429961/36587358-45d33516-1885-11e8-82a0-0378370895b8.png)

Is it possible to get a "text" version as in the example?

![image](https://user-images.githubusercontent.com/6429961/36587385-5d5f4dd2-1885-11e8-900f-e8dafdec1071.png)

Thanks.

**Comment by greg0ire** [comment]
This is really funny! Are you using gvim, maybe?

**Comment by lukepass** [comment]
Yes, I am!

P.S. greg0ire you are working on this project too? You are very active! I asked yesterday a question on SonataUserBundle :)

**Comment by greg0ire** [comment]
No, I'm just a fellow user, like you :) I contribute some wording fixes form time to time, but that's all

**Comment by dantleech** [comment]
Hey @lukepass 

Yes, that's the expected behavior of the `confirm` VIM function in gvim - I don't think it was originally designed to display the number of options that the context menu provides.

I think we would need to re-implement the functionality in vimscript to get it to behave better - but happy if there are other solutions.

I personally find VIM in the terminal a better experience however, especially when used in conjunction with tmux :D

**Comment by lukepass** [comment]
Ok, I think we can close this!
