### ISSUE TITLE
Error : Trying to create descendant from absolute path 

### ISSUE THREAD

**Issue by kermorgant** [phpactor/phpactor#479]
Hi,

I've stumbled on this error while trying to get class autocomplete working.

I have this example buffer 
```php
    public function commentNewAction(Request $request, Post $post)
    {
        $comment = new BlogComment();

        $form = $this->createForm(CommentType::class, $comment);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            /** @var Comment $comment */
            $comment = $form->getData();
            $comment->setAuthor($this->getUser());
            $comment->setPost($post);

            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($comment);
            $entityManager->flush();

            $event = new CommentEvent($comment);
            $event->get

```

The completion for ```$event->get``` works fine. But if I try to instantiate a var like ```$test = new Comm```, I got this error 

```
Result: (:message "Trying to create descendant from absolute path \"/home/mikael/workspace/sf-voyages/vendor/zendframework/zenddiagnostics/src\" that does not lie within context path \"/home/mikael/workspace/sf-voyages/\"" :details "0: Trying to create descendant from absolute path \"/home/mikael/workspace/sf-voyages/vendor/zendframework/zenddiagnostics/src\" that does not lie within context path \"/home/mikael/workspace/sf-voyages/\"\n#0 /home/mikael/src/phpactor/vendor/phpactor/source-code-filesystem/lib/Adapter/Composer/ComposerFileListProvider.php(66): Phpactor\\Filesystem\\Domain\\FilePath->makeAbsoluteFromString(Object(Phpactor\\Filesystem\\Domain\\FilePath))\n#1 /home/mikael/src/phpactor/vendor/phpactor/source-code-filesystem/lib/Domain/ChainFileListProvider.php(23): Phpactor\\Filesystem\\Adapter\\Composer\\ComposerFileListProvider->fileList()\n#2 /home/mikael/src/phpactor/vendor/phpactor/source-code-filesystem/lib/Adapter/Simple/SimpleFilesystem.php(32): Phpactor\\Filesystem\\Domain\\ChainFileListProvider->fileList()\n#3 /home/mikael/src/phpactor/vendor/phpactor/completion/lib/Bridge/TolerantParser/SourceCodeFilesystem/ScfClassCompletor.php(52): Phpactor\\Filesystem\\Adapter\\Simple\\SimpleFilesystem->fileList()\n#4 /home/mikael/src/phpactor/vendor/phpactor/completion/lib/Bridge/TolerantParser/ChainTolerantCompletor.php(44): Phpactor\\Completion\\Bridge\\TolerantParser\\SourceCodeFilesystem\\ScfClassCompletor->complete(Object(Microsoft\\PhpParser\\Node\\QualifiedName), '<?php\\n\\n/*\\n *\\n *...', 5621)\n#5 /home/mikael/src/phpactor/vendor/phpactor/completion/lib/Core/ChainCompletor.php(37): Phpactor\\Completion\\Bridge\\TolerantParser\\ChainTolerantCompletor->complete('<?php\\n\\n/*\\n *\\n *...', 5621)\n#6 /home/mikael/src/phpactor/lib/Extension/Completion/Application/Complete.php(21): Phpactor\\Completion\\Core\\ChainCompletor->complete('<?php\\n\\n/*\\n *\\n *...', 5621)\n#7 /home/mikael/src/phpactor/lib/Extension/Completion/Rpc/CompleteHandler.php(40): Phpactor\\Extension\\Completion\\Application\\Complete->complete('<?php\\n\\n/*\\n *\\n *...', 5621)\n#8 /home/mikael/src/phpactor/lib/Extension/Rpc/RequestHandler/RequestHandler.php(39): Phpactor\\Extension\\Completion\\Rpc\\CompleteHandler->handle(Array)\n#9 /home/mikael/src/phpactor/lib/Extension/Rpc/RequestHandler/ExceptionCatchingHandler.php(25): Phpactor\\Extension\\Rpc\\RequestHandler\\RequestHandler->handle(Object(Phpactor\\Extension\\Rpc\\Request))\n#10 /home/mikael/src/phpactor/lib/Extension/Rpc/RequestHandler/LoggingHandler.php(39): Phpactor\\Extension\\Rpc\\RequestHandler\\ExceptionCatchingHandler->handle(Object(Phpactor\\Extension\\Rpc\\Request))\n#11 /home/mikael/src/phpactor/lib/Extension/Rpc/Command/RpcCommand.php(74): Phpactor\\Extension\\Rpc\\RequestHandler\\LoggingHandler->handle(Object(Phpactor\\Extension\\Rpc\\Request))\n#12 /home/mikael/src/phpactor/lib/Extension/Rpc/Command/RpcCommand.php(62): Phpactor\\Extension\\Rpc\\Command\\RpcCommand->processRequest(Object(Phpactor\\Extension\\Rpc\\Request))\n#13 /home/mikael/src/phpactor/vendor/symfony/console/Command/Command.php(264): Phpactor\\Extension\\Rpc\\Command\\RpcCommand->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#14 /home/mikael/src/phpactor/vendor/symfony/console/Application.php(874): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#15 /home/mikael/src/phpactor/vendor/symfony/console/Application.php(228): Symfony\\Component\\Console\\Application->doRunCommand(Object(Phpactor\\Extension\\Rpc\\Command\\RpcCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#16 /home/mikael/src/phpactor/lib/Application.php(47): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#17 /home/mikael/src/phpactor/vendor/symfony/console/Application.php(130): Phpactor\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#18 /home/mikael/src/phpactor/bin/phpactor(43): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#19 {main}")
```

I've triggered this on an old dummy project codebase but I have the same on another one I'm currently working on.

What info could I give to debug that ?

Regards
Mikael

**Comment by dantleech** [comment]
It is saying that the longer path below is not within the base path
```
/home/mikael/workspace/sf-voyages/vendor/zendframework/zenddiagnostics/src
```

is not within the base path:

```
/home/mikael/workspace/sf-voyages/
```

But it clearly is, you can debug by adding

```
rpc.store_replay: true
```

to your `.phpactor.yml` file, then after you receive the message you can run

```
$ phpactor rpc --replay --verbose
```

to reproduce (or `cp ~/.local/share/phpactor/replay.json .` and `cat replay.json | phpactor rpc --verbose` to replay over and over).

This will give you the stack trace, bonus points if you can identify why it's happening [here](https://github.com/phpactor/source-code-filesystem/blob/master/lib/Domain/FilePath.php#L85) :)

**Comment by dantleech** [comment]
Did changing Phpactors project root solve the issue? In which case I wonder at the accuracy of that error message (what it is telling us seems valid).

**Comment by kermorgant** [comment]
Not yet.

For the record, I tried to configure the replay option with a .phpactor.yml file at the root of the project. But , I did not get a replay.json file until I copied .phpactor.yml to src/AppBundle/Controller

For now, I've tried various things in elisp, trying to see if the phpactor-status command of the emacs package would indicate that the config file at the root of the project would be recognized, but no luck so far.

In the elisp code, I noticed phpactor rpc is invoked with --working-dir option, and the value seemed correct to me. Could it be that it's been ignored by phpactor ? 

I'm running out of time now, I'll try to take a look at it later

**Comment by dantleech** [comment]
No, the working dir option works fine. As a side-note you can also put the config in a more global config file, e.g. `~/.config/phpactor/phpactor.yml`.

**Comment by kermorgant** [comment]
indeed, I guess it could be a workaround.
But I've been using phpactor-status' output as a shortcut (avoiding to check if a replay file was generated or not) when trying different things.

I guess I'll have to look at the php side a bit to see what happens during those tests.

**Comment by dantleech** [comment]
If you put it in `.config` it will _always_ be generated, and it will use the same location each time, so you can just take it for granted then.

**Comment by kermorgant** [comment]
I just noticed using xdebug on phpactor that the working-dir parameter of the rpc command used from the emacs was *not* found as I expected in the $paths attribute of Phpactor\Extemsion\Core\Rpc\StatusHandler.

Instead, I found the path of a previously navigated project.

**Comment by kermorgant** [comment]
I tested your last pr fixing the status, but still got the error.

I think I've found the origin of it but I'm short of time so haven't tested a fix.

In FilePath.php, you have this

```php
    public function isWithin(FilePath $path)
    {
        return 0 === strpos($this->path(), $path->path().'/');
    }
```

I guess the ```.'/'``` adds an extra ```/``` which provokes a failure, as there already an ending ```/``` in the $path.

**Comment by dantleech** [comment]
We could probably still sanitize the _incoming_ path however..

**Comment by citlacom** [comment]
Hi @dantleech - Can you confirm if this issue is fixed? I'm experimenting similar problem using phpactor on Drupal 8 project with NeoVim an deoplete autocomplete plugin, here is the error trace:

`[2019-02-19 20:17:02] phpactor.ERROR: RESPONSE {"action":"error","parameters":{"message":"Trying to create descendant from absolute path \"/Users/pablocc/Sites/therefore/rm8-drupal-src/vendor/mikey179/vfsStream/src/main/php\" that does not lie within context path \"/Users/pablocc/Sites/therefore/rm8-drupal-src/docroot/core\"","details":"0: Trying to create descendant from absolute path \"/Users/pablocc/Sites/therefore/rm8-drupal-src/vendor/mikey179/vfsStream/src/main/php\" that does not lie within context path \"/Users/pablocc/Sites/therefore/rm8-drupal-src/docroot/core\"\n#0 /Users/pablocc/.local/share/nvim/bundle/phpactor/vendor/phpactor/source-code-filesystem/lib/Adapter/Composer/ComposerFileListProvider.php(66): Phpactor\\Filesystem\\Domain\\FilePath->makeAbsoluteFromString(Object(Phpactor\\Filesystem\\Domain\\FilePath))\n#1 /Users/pablocc/.local/share/nvim/bundle/phpactor/vendor/phpactor/source-code-filesystem/lib/Domain/ChainFileListProvider.php(23): Phpactor\\Filesystem\\Adapter\\Composer\\ComposerFileListProvider->fileList()\n#2 /Users/pablocc/.local/share/nvim/bundle/phpactor/vendor/phpactor/source-code-filesystem/lib/Adapter/Simple/SimpleFilesystem.php(32): Phpactor\\Filesystem\\Domain\\ChainFileListProvider->fileList()\n#3 /Users/pablocc/.local/share/nvim/bundle/phpactor/vendor/phpactor/completion/lib/Bridge/TolerantParser/SourceCodeFilesystem/ScfClassCompletor.php(51): Phpactor\\Filesystem\\Adapter\\Simple\\SimpleFilesystem->fileList()\n#4 /Users/pablocc/.local/share/nvim/bundle/phpactor/vendor/phpactor/completion/lib/Bridge/TolerantParser/LimitingCompletor.php(35): Phpactor\\Completion\\Bridge\\TolerantParser\\SourceCodeFilesystem\\ScfClassCompletor->complete(Object(Microsoft\\PhpParser\\Node\\QualifiedName), '<?php\\n\\nnamespac...', 1176)\n#5 /Users/pablocc/.local/share/nvim/bundle/phpactor/vendor/phpactor/completion/lib/Bridge/TolerantParser/ChainTolerantCompletor.php(52): Phpactor\\Completion\\Bridge\\TolerantParser\\LimitingCompletor->complete(Object(Microsoft\\PhpParser\\Node\\QualifiedName), '<?php\\n\\nnamespac...', 1176)\n#6 /Users/pablocc/.local/share/nvim/bundle/phpactor/vendor/phpactor/completion/lib/Core/ChainCompletor.php(25): Phpactor\\Completion\\Bridge\\TolerantParser\\ChainTolerantCompletor->complete('<?php\\n\\nnamespac...', 1176)\n#7 [internal function]: Phpactor\\Completion\\Core\\ChainCompletor->complete('<?php\\n\\nnamespac...', 1176)\n#8 /Users/pablocc/.local/share/nvim/bundle/phpactor/vendor/phpactor/completion-rpc-extension/lib/Handler/CompleteHandler.php(54): iterator_to_array(Object(Generator))\n#9 /Users/pablocc/.local/share/nvim/bundle/phpactor/vendor/phpactor/rpc-extension/lib/RequestHandler/RequestHandler.php(33): Phpactor\\Extension\\CompletionRpc\\Handler\\CompleteHandler->handle(Array)\n#10 /Users/pablocc/.local/share/nvim/bundle/phpactor/vendor/phpactor/rpc-extension/lib/RequestHandler/ExceptionCatchingHandler.php(25): Phpactor\\Extension\\Rpc\\RequestHandler\\RequestHandler->handle(Object(Phpactor\\Extension\\Rpc\\Request))\n#11 /Users/pablocc/.local/share/nvim/bundle/phpactor/vendor/phpactor/rpc-extension/lib/RequestHandler/LoggingHandler.php(39): Phpactor\\Extension\\Rpc\\RequestHandler\\ExceptionCatchingHandler->handle(Object(Phpactor\\Extension\\Rpc\\Request))\n#12 /Users/pablocc/.local/share/nvim/bundle/phpactor/vendor/phpactor/rpc-extension/lib/Command/RpcCommand.php(86): Phpactor\\Extension\\Rpc\\RequestHandler\\LoggingHandler->handle(Object(Phpactor\\Extension\\Rpc\\Request))\n#13 /Users/pablocc/.local/share/nvim/bundle/phpactor/vendor/phpactor/rpc-extension/lib/Command/RpcCommand.php(68): Phpactor\\Extension\\Rpc\\Command\\RpcCommand->processRequest(Object(Phpactor\\Extension\\Rpc\\Request))\n#14 /Users/pablocc/.local/share/nvim/bundle/phpactor/vendor/symfony/console/Command/Command.php(255): Phpactor\\Extension\\Rpc\\Command\\RpcCommand->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#15 /Users/pablocc/.local/share/nvim/bundle/phpactor/vendor/symfony/console/Application.php(901): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#16 /Users/pablocc/.local/share/nvim/bundle/phpactor/vendor/symfony/console/Application.php(262): Symfony\\Component\\Console\\Application->doRunCommand(Object(Phpactor\\Extension\\Rpc\\Command\\RpcCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#17 /Users/pablocc/.local/share/nvim/bundle/phpactor/lib/Application.php(50): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#18 /Users/pablocc/.local/share/nvim/bundle/phpactor/vendor/symfony/console/Application.php(145): Phpactor\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#19 /Users/pablocc/.local/share/nvim/bundle/phpactor/bin/phpactor(41): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#20 {main}"}} []`

If you can provide me some hints why this issue could be occurring I can try to troubleshoot and implement a fix in case this is still open. I will configure the replay and see if I'm able to find more details on the issue.

Thanks for your help and for this great tool, the autocomplete is pretty amazing, I have been using VIM for 9 years and as I have not found a good solution for classes/methods navigation and autocomplete in VIM was tempted to move to PhpStorm but I did some research before the switch and found your plugin. I feel so happy to stick to VIM, well, almost... during this research also decided to move to NeoVim but is almost the same, right?
