### ISSUE TITLE
Go to symbol referenced in docblock

### ISSUE THREAD

**Issue by weirdan** [phpactor/phpactor#494]
```php
/**
 * @param A<>|B $p
 */
function f($p): void {}
```
Assume the cursor is in the '<>' position. It would be great if PHPActor would be able to navigate (and, ideally, support all other features like context menu from that point) to `A`s definition, like it can when `A` is referenced in executable code.

Currently it complains about 'symbol type <unknown>'

**Comment by dantleech** [comment]
Yep, will probably need to enable this in WorseReflection.

**Comment by dantleech** [comment]
Have been looking at this, it's tricky. In order to do it properly we need to be able to reflect the docblock itself (f.e. using the [phpstan docblock parser](https://github.com/phpstan/phpdoc-parser). This means injecting more responsiblity into WorseReflection, and the current architecture isn't very open to this. 

We could do this in a naieve way the Phpactor GotoDefinition code: if the Symbol type is `<unknown>` then assume that the current word is a class name and resolve that to an FQN (there is some functionality exposed for this purpose from WR).

**Comment by dantleech** [comment]
This was done in #679
