### ISSUE TITLE
[vim-plugin] Unknown option `--layout=reverse-list` with old version of FZF

### ISSUE THREAD

**Issue by dantleech** [phpactor/phpactor#838]
FZF is used for some actions automatically. It seems that this option is not present until version 0.17.4 (2018).

Wonder if it's worth checking the FZF version before using it?

**Comment by elythyr** [comment]
I would say no, it's an old version enough so there will not be a lot of cases.
Plus we added FZF recently so it reduces the chances a lot more since a lot of user might just have installed FZF to try the new features.

But I guess it won't be to hard to do by parsing the result of `fzf --version` or maybe the plugin already does it.
