### ISSUE TITLE
Generate PHP docs

### ISSUE THREAD

**Issue by zordsdavini** [phpactor/phpactor#840]
In ViM I miss only one thing compared to phpStorm. Do you have any plans on it?

**Comment by dantleech** [comment]
Not yet, but consider this a feature request :)

You _should_ be able to customize the new method / class [template](https://phpactor.github.io/phpactor/templates.html) to include documentation, but not sure.

**Comment by zordsdavini** [comment]
Thank you for answer. For projects what I am working this phpDoc is needed. But this feature should not be as template feature (in my case), because as developer you often change argument or return types. There should be command to generate for current method/class etc. 
Ex., if you are in method scope (from ViM), :call phpactor#generateMethodDoc or something.
For class/interface/trait it should have one method as it is similar.
It would be nice to have possibility to change template.
From code in phpactor reflection I understand that it can do some work with: name, parameters. Doesn't find return but it should be and I doubt about @throw tags.
If I'll find time I'll try to create some extension prototype

**Comment by dantleech** [comment]
Hmm, creating docblocks is easy enough, updating them is currently an unsolved problem in Phpactor (think property types). Fortunately we have property types in PHP 7.4, but that's still a way off for most people.

We need a docblock Parser which registers the start/end offers for tokens, Phpactor's "parser" does not do this and neither does, nor AFAIK do the Phpstan and Phpdoc  parsers. (I think the phpdoc parser is unsuitable in any case as it uses runtime Reflection)


On 15 November 2019 07:47:21 CET, "Arnas Udovičius" <notifications@github.com> wrote:
>Thank you for answer. For projects what I am working this phpDoc is
>needed. But this feature should not be as template feature (in my
>case), because as developer you often change argument or return types.
>There should be command to generate for current method/class etc. 
>Ex., if you are in method scope (from ViM), :call
>phpactor#generateMethodDoc or something.
>For class/interface/trait it should have one method as it is similar.
>It would be nice to have possibility to change template.
>From code in phpactor reflection I understand that it can do some work
>with: name, parameters. Doesn't find return but it should be and I
>doubt about @throw tags.
>If I'll find time I'll try to create some extension prototype
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/phpactor/phpactor/issues/840#issuecomment-554236232

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by zordsdavini** [comment]
The updating is not needed because mostly you will delete old and generate new but if you want preserve some annotations, then you will need manual work. This simple approach could help a lot. Many IDEs do only that and all happy

**Comment by dantleech** [comment]
Potentially -  but then you could argue that the value in such docblocks is the documentation - the actual prose text, which would also be deleted and possibly other things which cannot be auto-inferred, or which are currently not available to us, e.g. `@throws` etc.

**Comment by sstutz** [comment]
I found this a while back, might be worth mentioning https://github.com/kkoomen/vim-doge

**Comment by zordsdavini** [comment]
thanks @sstutz , will try. But about doc generation in Phpactor I still thinking

**Comment by zordsdavini** [comment]
@sstutz I could not get `vim-doge` working. Less of documentation how to configure. Will look toward `phpactor` possibilities

**Comment by sstutz** [comment]
@zordsdavini I just set it up and it works like a charm. Make sure that you've phpdoc installed, it is not part of the default php installation!

On my system it's called "phpdocumentor2", with it innstalled all I did was install vim-dodge, put my curos *on the method signature* and hit <leader>d

**Comment by gitbugr** [comment]
I am particularly looking forward to this because of the kinds of phpdoc generation that phpactor will be able to provide vs other plugins.

for example `@throws` if there is a method in the ast that throws any kind of exception. That's something impossible for plugins I've tried that basically just look at the params and return type, and shove in a template.

This is something my coworkers who use PHPStorm get, that I don't. /:

**Comment by elythyr** [comment]
I would say that exception should be exceptional enough so that it is not an issue to had them manually :)
For my point of view the phpdoc should either gave functional information (the prose like @dantleech said) or and aid for the IDE.
With PHP 7.4 we won't have the need for that, except when using some kind of `iterable`.
The phpdoc should be used as little as possible, php-cs-fixer even add a new fixer to remove superfluous tags.

So I won't make it a priority right now I think, but you could always try to propose a PR.
It would be very nice as an extension.

**Comment by likelxl** [comment]
now, can it work? how to use?

**Comment by NSLog0** [comment]
How to use it. I'm trying many functions, still got nothing

**Comment by elythyr** [comment]
> now, can it work? how to use?

> How to use it. I'm trying many functions, still got nothing

There was no changes related to this since the issue was created so it's still not possible.
IMO it's not a priority and would most likely not be before a long time.

One big limitation is that there is no phpdoc parser that gave the position in a file of each nodes of a parsed phpdoc.
Since the phpdoc is not part of the PHP language but was added to provide some missing features in the language (like type hints before 7.4) it's not supported by PHP parsers (as far as I know) and require a separated parser.
Two parsers means that the information about the phpdoc is not part of the AST we used to operate on the code, that's why when you rename a class we are able to rename it everywhere in the project **except** in the phpdoc.

As mentioned by @sstutz [doge](https://github.com/kkoomen/vim-doge) could help you, I stop carrying about phpdoc by the time I discover so I never tried it myself.

**Comment by NSLog0** [comment]
Ok, then what the alternative plugin for creating phpdoc?

**Comment by dantleech** [comment]
You can check, for example: https://vimawesome.com/?q=php+doc

**Comment by elythyr** [comment]
Doge as mentioned might be a solution.

phpdoc and docblocks are the same thing.

**Comment by weeman1337** [comment]
It is true that PHP 7.4 makes doc blocks for type hints partially obselete. But there are cases where you might want to have them. An example are generics like `@return array<string>`.

Another thing from a real-life policy: Either there is no doc block at all - or if you have something important to tell all the params have to be included. Furthermore there are projects with policys out there that force you to have doc blocks.

So +1 from my side as an useful feature. My list is long. But once all other things I need are done maybe I will have a look. Of course if anyone other wants to implement that - go :smiley:  :rocket:

**Comment by dantleech** [comment]
Yes -- it would work with complex types, but then Phpactor's type system is still nowhere near as good as Psalm/Phpstan. Not sure it's worth the effort currently.

**Comment by dantleech** [comment]
There is now a add "missing" docblock refactoring which will try and add _necessary_ docblocks that are inferred from the function/method return type. Closing this for now but feel free to continue the discussion.
