### ISSUE TITLE
[develop] `inputlist` strategy is forced for collection actions when FZF is used

### ISSUE THREAD

**Issue by dantleech** [phpactor/phpactor#845]
The FZF input selector does not work as expected with collection items apparently.

We introduced a hack to force the choice strategy to `inputlist` in #843. See this issue for details

**Comment by chinleung** [comment]
Is this why my import list is no longer searchable? 🤔 Was about to make an issue for that. Basically, when I run `phpactor#UseAdd()`, I used to get a buffer with the list of namespaces and I could search through the list to quickly import the right namespace but now it is simply a list where I can only enter a number.

**Comment by dantleech** [comment]
I guess you were using the `develop` branch?

Yes you can enable the FZF stuff as detailed here :) https://phpactor.github.io/phpactor/vim-plugin/experimental.html

**Comment by chinleung** [comment]
> I guess you were using the `develop` branch?
> 
> Yes you can enable the FZF stuff as detailed here :) https://phpactor.github.io/phpactor/vim-plugin/experimental.html

Thanks! Yes I'm using the `develop` branch and that's exactly what I was looking for. It is working properly now. 😄

**Comment by dshoreman** [comment]
This was posted [in a comment][1] on #1218 by @camilledejoye:

> We really need to take care of those lists issues, I still haven't found a solution for the fzf issue with multiple lists and I don't think we will ever found one...
> Maybe we could take a look at [liuchengxu/vim-clap](https://github.com/liuchengxu/vim-clap) instead.

@camilledejoye I haven't used it yet, but wouldn't it suffer the same issues as fzf?

The examples only seem to mention calling "commands" saved in .vimrc, but if we're able to call it with a command directly then it *could* work. If the issue with fzf is calling it in a loop though, how would that process go with vim-clap?

> Since it runs directly in vim I hope we won't have the same issues, it forces us to add an extra dependency though but it should be acceptable as an optional feature.

As it's a soft dependency we'd probably be ok (much like fzf). Since list.vim already checks for collections, we could update it to `isCollection && !hasVimClap` with an extra case for vim-clap in `auto_detect_strategy()`. For anyone without clap, it'd work as it did before

[1]: https://github.com/phpactor/phpactor/issues/1218#issuecomment-792553011
