### ISSUE TITLE
[improvement] Generates decorator basic structure

### ISSUE THREAD

**Issue by camilledejoye** [phpactor/phpactor#859]
Hi,

Just to put it somewhere before I forgot.
It could be interesting to have a functionality which works like `implements contracts` but will also add in the body of every methods a forward call to the same method for the decorated object.

The more method you got to implement, the more painful it is.
I think it could be a good way to encourage composition over inheritance too :)

**Comment by dantleech** [comment]
Phpstan will complain if you don't call the parent method IIRC. Could easily add a config flag and default to calling the parent when overriding concrete methods.

**Comment by elythyr** [comment]
> Phpstan will complain if you don't call the parent method IIRC

Not sure to understand what you mean.

> Could easily add a config flag and default to calling the parent when overriding concrete methods.

There is no parent here because it's about composition, not inheritance, but yes we should reuse what is currently done for the `implement contracts`.
But maybe not with a flag since we also need to create a constructor which will take an instance of the decorated interface.
So the use of a flag might add to many responsibilities.
We also need a custom handler so that when implementing multiple interfaces the use can choose which one to decorate.

**Comment by dantleech** [comment]
Ah ok - I see. I am talking about the default behavior of overriding methods.

Yes this is another thing. I originally thought to do this as an [https://github.com/phpactor/code-transform/blob/master/lib/Domain/GenerateFromExisting.php] generator (this is how we extract [interfaces](https://github.com/phpactor/phpactor/blob/develop/lib/Extension/CodeTransformExtra/CodeTransformExtraExtension.php#L365).

But open to other suggestions.

**Comment by dantleech** [comment]
done in #1879
