### ISSUE TITLE
Cannot run phpactor with an extra config key

### ISSUE THREAD

**Issue by przepompownia** [phpactor/phpactor#914]
Let's assume that you have a global config with a key accepted by any non-default extension e.g. ` language_server_completion.provide_text_edit`. Then install phpactor somewhere else, but under the same global configuration. Run `composer install` and `./bin/phpactor`.

Do you get a message of form
```
In Resolver.php line 54:
                                                                                                                                                                             
  Key(s) "language_server_completion.provide_text_edit" are not known, known keys: "console_dumper_default", ...
```
?

Probably it should not break phpactor, but warn only.

**Comment by dantleech** [comment]
Hmm, possibly, but it's not [designed this way currently](https://github.com/phpactor/map-resolver/blob/master/lib/Resolver.php#L49).

**Comment by przepompownia** [comment]
It probably would be simply done by `$config = array_intersect_key($config, array_flip($allowedKeys));` with passing a warning message instead , but I have no idea how to correctly pass it to the application in order to show it as warning.

**Comment by mamazu** [comment]
To be fair I have also run into the same issue with phpactor. Copied the config to a new machine and it crashed because I was using an old version that didn't have all the settings yet. (Which in this case reminded me to upgrade the phpactor server.)

*But* I find that errors (especially helpful ones) are much better than warnings. For two reasons mainly: 
* Would it show the message in the vim or vscode or emacs plugin if the server didn't completely crash?
* What if you add a key that has an extra `s` at the end, and you just run the config and the feature is still not working because the correct key is still missing.

With all that being said, I think the possible benefits it could have don't really outweigh the work and hassle that it creates.

**Comment by dantleech** [comment]
as of a year or two Phpactor will not crash and will issue a warning on unknown keys as per this ticket !
